[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "flashcard"
version = "0.1.0"
description = "flashcards for studying with!"
requires-python = ">=3.8"
dependencies = [
    "pandas",
    "odfpy",
    "openpyxl"
]

[project.optional-dependencies]
dev = [
    "pytest",
    "black",
    "flake8",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["flashcard*"]